export const PERFIL = {
  MECANICO: 'MECANICO',
  LIDER: 'LIDER',
  ADMIN: 'ADMIN',
} as const;
export type Perfil = (typeof PERFIL)[keyof typeof PERFIL];

export const USER_STATUS = {
  ATIVO: 'ATIVO',
  BLOQUEADO: 'BLOQUEADO',
  PENDENTE: 'PENDENTE',
} as const;
export type UserStatus = (typeof USER_STATUS)[keyof typeof USER_STATUS];

export const DEPOSITO_STATUS = {
  ATIVO: 'ATIVO',
  INATIVO: 'INATIVO',
} as const;
export type DepositoStatus = (typeof DEPOSITO_STATUS)[keyof typeof DEPOSITO_STATUS];

export const ITEM_STATUS = {
  ATIVO: 'ATIVO',
  INATIVO: 'INATIVO',
  REMOVIDO_DA_LISTA_OFICIAL: 'REMOVIDO_DA_LISTA_OFICIAL',
  ALTERADO: 'ALTERADO',
  PENDENTE_DE_REVISAO: 'PENDENTE_DE_REVISAO',
} as const;
export type ItemStatus = (typeof ITEM_STATUS)[keyof typeof ITEM_STATUS];

export const VERSION_STATUS = {
  PUBLICADA: 'PUBLICADA',
  SUBSTITUIDA: 'SUBSTITUIDA',
  RESTAURADA: 'RESTAURADA',
} as const;
export type VersionStatus = (typeof VERSION_STATUS)[keyof typeof VERSION_STATUS];

export const ORIGEM_MOVIMENTACAO = {
  ONLINE: 'ONLINE',
  OFFLINE: 'OFFLINE',
} as const;
export type OrigemMovimentacao = (typeof ORIGEM_MOVIMENTACAO)[keyof typeof ORIGEM_MOVIMENTACAO];

export const TIPO_MOVIMENTACAO_SPARE_PART = {
  ENTRADA: 'ENTRADA',
  SAIDA: 'SAIDA',
  USO_CORRECAO: 'USO_CORRECAO',
  TRANSFERENCIA_INFORMATIVA: 'TRANSFERENCIA_INFORMATIVA',
  CONVERSAO_ACEITA: 'CONVERSAO_ACEITA',
  DESCARTE: 'DESCARTE',
  AJUSTE_AUTORIZADO: 'AJUSTE_AUTORIZADO',
  DEVOLUCAO_CORRECAO: 'DEVOLUCAO_CORRECAO',
} as const;
export type TipoMovimentacaoSparePart =
  (typeof TIPO_MOVIMENTACAO_SPARE_PART)[keyof typeof TIPO_MOVIMENTACAO_SPARE_PART];

export const ORIGEM_SPARE_PART = {
  BACKLOG: 'BACKLOG',
  OUTRA_FRENTE: 'OUTRA_FRENTE',
  COMPRA_DEBITO_DIRETO: 'COMPRA_DEBITO_DIRETO',
  LIDERANCA: 'LIDERANCA',
  OUTRO: 'OUTRO',
} as const;
export type OrigemSparePart = (typeof ORIGEM_SPARE_PART)[keyof typeof ORIGEM_SPARE_PART];

export const SUGESTAO_STATUS = {
  PENDENTE: 'PENDENTE',
  ACEITA: 'ACEITA',
  RECUSADA: 'RECUSADA',
  CANCELADA: 'CANCELADA',
  EXPIRADA: 'EXPIRADA',
} as const;
export type SugestaoStatus = (typeof SUGESTAO_STATUS)[keyof typeof SUGESTAO_STATUS];

export const REQUEST_STATUS = {
  RASCUNHO: 'RASCUNHO',
  PRONTA_PARA_ENVIO: 'PRONTA_PARA_ENVIO',
  ENVIADA: 'ENVIADA',
  RECEBIDA_PELA_LIDERANCA: 'RECEBIDA_PELA_LIDERANCA',
  APROVADA: 'APROVADA',
  ATENDIDA: 'ATENDIDA',
  CANCELADA: 'CANCELADA',
} as const;
export type RequestStatus = (typeof REQUEST_STATUS)[keyof typeof REQUEST_STATUS];

export const TIPO_CORRECAO = {
  APENAS_REGISTRAR_DIVERGENCIA: 'APENAS_REGISTRAR_DIVERGENCIA',
  CORRIGIR_COM_PECA_AVULSA: 'CORRIGIR_COM_PECA_AVULSA',
  AGUARDAR_REPOSICAO: 'AGUARDAR_REPOSICAO',
  ACAO_LIDERANCA: 'ACAO_LIDERANCA',
  OUTRA: 'OUTRA',
} as const;
export type TipoCorrecao = (typeof TIPO_CORRECAO)[keyof typeof TIPO_CORRECAO];

export const INSPECTION_STATUS = {
  EM_ANDAMENTO: 'EM_ANDAMENTO',
  CONCLUIDA: 'CONCLUIDA',
  REVISADA: 'REVISADA',
} as const;
export type InspectionStatus = (typeof INSPECTION_STATUS)[keyof typeof INSPECTION_STATUS];

export const INSPECTION_ITEM_STATUS = {
  OK: 'OK',
  DIVERGENTE: 'DIVERGENTE',
  PENDENTE: 'PENDENTE',
} as const;
export type InspectionItemStatus =
  (typeof INSPECTION_ITEM_STATUS)[keyof typeof INSPECTION_ITEM_STATUS];

export const DIVERGENCIA_STATUS = {
  ABERTA: 'ABERTA',
  EM_ANALISE: 'EM_ANALISE',
  RESOLVIDA: 'RESOLVIDA',
  CANCELADA: 'CANCELADA',
} as const;
export type DivergenciaStatus = (typeof DIVERGENCIA_STATUS)[keyof typeof DIVERGENCIA_STATUS];

export const DIVERGENCIA_TIPO = {
  SALDO_NEGATIVO: 'SALDO_NEGATIVO',
  CONFERENCIA: 'CONFERENCIA',
  REPOSICAO: 'REPOSICAO',
} as const;
export type DivergenciaTipo = (typeof DIVERGENCIA_TIPO)[keyof typeof DIVERGENCIA_TIPO];

export const LOG_TIPO = {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  BLOQUEIO_INATIVIDADE: 'BLOQUEIO_INATIVIDADE',
  TROCA_USUARIO: 'TROCA_USUARIO',
  CADASTRO_USUARIO: 'CADASTRO_USUARIO',
  CRIACAO_USUARIO: 'CRIACAO_USUARIO',
  EDICAO_USUARIO: 'EDICAO_USUARIO',
  BAIXA: 'BAIXA',
  ESTORNO: 'ESTORNO',
  CONFERENCIA: 'CONFERENCIA',
  CORRECAO: 'CORRECAO',
  REPOSICAO: 'REPOSICAO',
  ENTRADA_PECA_AVULSA: 'ENTRADA_PECA_AVULSA',
  SAIDA_PECA_AVULSA: 'SAIDA_PECA_AVULSA',
  SUGESTAO_CRIADA: 'SUGESTAO_CRIADA',
  SUGESTAO_ACEITA: 'SUGESTAO_ACEITA',
  SUGESTAO_RECUSADA: 'SUGESTAO_RECUSADA',
  CONVERSAO_PECA_AVULSA: 'CONVERSAO_PECA_AVULSA',
  CRIACAO_DEPOSITO: 'CRIACAO_DEPOSITO',
  EDICAO_DEPOSITO: 'EDICAO_DEPOSITO',
  DESATIVACAO_DEPOSITO: 'DESATIVACAO_DEPOSITO',
  DESIGNACAO_DEPOSITO: 'DESIGNACAO_DEPOSITO',
  REVOGACAO_DEPOSITO: 'REVOGACAO_DEPOSITO',
  IMPORTACAO_FOLHA: 'IMPORTACAO_FOLHA',
  PUBLICACAO_ENXOVAL: 'PUBLICACAO_ENXOVAL',
  EDICAO_ENXOVAL: 'EDICAO_ENXOVAL',
  RESTAURACAO: 'RESTAURACAO',
  SINCRONIZACAO: 'SINCRONIZACAO',
  CONFLITO: 'CONFLITO',
  DIVERGENCIA: 'DIVERGENCIA',
  BACKUP_RESTAURACAO: 'BACKUP_RESTAURACAO',
  SOLICITACAO_CRIADA: 'SOLICITACAO_CRIADA',
  SOLICITACAO_ATUALIZADA: 'SOLICITACAO_ATUALIZADA',
  SOLICITACAO_ENVIADA: 'SOLICITACAO_ENVIADA',
  SOLICITACAO_APROVADA: 'SOLICITACAO_APROVADA',
  SOLICITACAO_ATENDIDA: 'SOLICITACAO_ATENDIDA',
  SOLICITACAO_CANCELADA: 'SOLICITACAO_CANCELADA',
} as const;
export type LogTipo = (typeof LOG_TIPO)[keyof typeof LOG_TIPO];

export const SYNC_STATUS = {
  SINCRONIZADO: 'SINCRONIZADO',
  OFFLINE_SEM_PENDENCIA: 'OFFLINE_SEM_PENDENCIA',
  OFFLINE_COM_PENDENCIA: 'OFFLINE_COM_PENDENCIA',
  SINCRONIZANDO: 'SINCRONIZANDO',
  ERRO_SINCRONIZACAO: 'ERRO_SINCRONIZACAO',
  CONFLITO_PENDENTE: 'CONFLITO_PENDENTE',
} as const;
export type SyncStatus = (typeof SYNC_STATUS)[keyof typeof SYNC_STATUS];

export const SYNC_QUEUE_STATUS = {
  PENDENTE: 'PENDENTE',
  ENVIANDO: 'ENVIANDO',
  ERRO: 'ERRO',
  ENVIADO: 'ENVIADO',
} as const;
export type SyncQueueStatus = (typeof SYNC_QUEUE_STATUS)[keyof typeof SYNC_QUEUE_STATUS];

export const SYNC_ENTITY = {
  BAIXA: 'BAIXA',
  CONFERENCIA: 'CONFERENCIA',
  CORRECAO: 'CORRECAO',
  ESTORNO: 'ESTORNO',
  SUGESTAO_ACEITA: 'SUGESTAO_ACEITA',
  SUGESTAO_RECUSADA: 'SUGESTAO_RECUSADA',
  SPARE_PART_ENTRADA: 'SPARE_PART_ENTRADA',
  SPARE_PART_SAIDA: 'SPARE_PART_SAIDA',
  SOLICITACAO: 'SOLICITACAO',
  DOCUMENTO: 'DOCUMENTO',
  LOG: 'LOG',
} as const;
export type SyncEntity = (typeof SYNC_ENTITY)[keyof typeof SYNC_ENTITY];

export const SNAPSHOT_TIPO = {
  ANTES: 'ANTES',
  DEPOIS: 'DEPOIS',
} as const;
export type SnapshotTipo = (typeof SNAPSHOT_TIPO)[keyof typeof SNAPSHOT_TIPO];

export const DOCUMENTO_TIPO = {
  FOTO: 'FOTO',
  PDF: 'PDF',
} as const;
export type DocumentoTipo = (typeof DOCUMENTO_TIPO)[keyof typeof DOCUMENTO_TIPO];

export const OCR_CONFIANCA = {
  ALTA: 'ALTA',
  BAIXA: 'BAIXA',
  AUSENTE: 'AUSENTE',
  INVALIDO: 'INVALIDO',
} as const;
export type OcrConfianca = (typeof OCR_CONFIANCA)[keyof typeof OCR_CONFIANCA];

export const SOLICITACAO_TIPO = {
  CONSUMIVEL: 'CONSUMIVEL',
  EPI: 'EPI',
} as const;
export type SolicitacaoTipo = (typeof SOLICITACAO_TIPO)[keyof typeof SOLICITACAO_TIPO];

export const TIPO_MOVIMENTACAO_ESTOQUE = {
  ENTRADA: 'ENTRADA',
  SAIDA: 'SAIDA',
  AJUSTE: 'AJUSTE',
} as const;
export type TipoMovimentacaoEstoque =
  (typeof TIPO_MOVIMENTACAO_ESTOQUE)[keyof typeof TIPO_MOVIMENTACAO_ESTOQUE];